title: Data-pipeline-for-Youtube-trending-videos-dataset
author: Takreem Akhter
email: akhtertakreem@gmail.com
description: > # this means to ignore newlines until "baseurl:"
# social links
linkedin_username: takreem-akhter # DO NOT include the @ character, or else the build will fail!
github_username:  TakreemAkhter # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
